version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: acklab_es01
    hostname: elasticsearch
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ${PWD}/elasticsearch/config:/usr/share/elasticsearch/config
      - ${PWD}/elasticsearch/logs:/usr/share/elasticsearch/logs
      - ${PWD}/elasticsearch/data:/usr/share/elasticsearch/data
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: acklab_kib01
    hostname: kibana
    ports:
      - "5601:5601"
    volumes:
      - ${PWD}/kibana/config:/usr/share/kibana/config
      - ${PWD}/kibana/data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
        
  logstash:
    image: docker.elastic.co/logstash/logstash:7.8.0
    container_name: acklab_log01
    hostname: logstash
    ports:
      - "5141:5141"
    volumes:
      - ${PWD}/logstash/pipeline:/usr/share/logstash/pipeline
      - ${PWD}/logstash/data:/usr/share/logstash/data
      - ${PWD}/logstash/config:/usr/share/config
    depends_on:
      - elasticsearch

volumes:
  es_data01:
  kibana_data01:
  logstash_data01:
