version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_logs:/usr/share/elasticsearch/logs
      - es_data:/usr/share/elasticsearch/data
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    volumes:
      - kibana/config:/usr/share/kibana/config/
      - kibana_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
        
  logstash:
    image: docker.elastic.co/logstash/logstash:7.8.0
    container_name: logstash
    hostname: logstash
    ports:
      - "5141:5141"
    volumes:
      - logstash/pipeline:/usr/share/logstash/pipeline/
      - logstash_data:/usr/share/logstash/data
    depends_on:
      - elasticsearch

volumes:
  es_data:
  es_logs:
  kibana_data:
  logstash_data:
  logstash/pipeline:
  kibana/config:
